# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EdookitMcp < Formula
  desc "Unofficial MCP connector for Edookit (Czech school information system)"
  homepage "https://github.com/dsaiko/edookit-mcp"
  version "0.1.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dsaiko/edookit-mcp/releases/download/v0.1.10/edookit-mcp_0.1.10_Darwin_x86_64.tar.gz"
      sha256 "bdf175207326d0742e6c96edff7dcf1979eec0b18f84921d444fe4ecac19f53e"

      define_method(:install) do
        bin.install "edookit-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dsaiko/edookit-mcp/releases/download/v0.1.10/edookit-mcp_0.1.10_Darwin_arm64.tar.gz"
      sha256 "896ee4147709452798b88bd8ccbd019b11025b140e0a87d7e11df59fae8caae9"

      define_method(:install) do
        bin.install "edookit-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dsaiko/edookit-mcp/releases/download/v0.1.10/edookit-mcp_0.1.10_Linux_x86_64.tar.gz"
      sha256 "63cac5a52db4992da3054216fab0068a3c2c0259186c6c6dfbd558a05d6d2a61"
      define_method(:install) do
        bin.install "edookit-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dsaiko/edookit-mcp/releases/download/v0.1.10/edookit-mcp_0.1.10_Linux_arm64.tar.gz"
      sha256 "43eb024675a560b918b49479226d325a7c7f51eac688b2badc032db7765c517c"
      define_method(:install) do
        bin.install "edookit-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      edookit-mcp requires Google Chrome (or any Chromium-family browser) installed
      on the host — it drives a real browser instance once per ~10 hours to log into
      Plus4U OIDC and capture the session cookie.

      Configuration is via environment variables (EDOOKIT_URL, EDOOKIT_USER, EDOOKIT_PASS).
      See https://github.com/dsaiko/edookit-mcp#-pro-uživatele for full setup.
    EOS
  end

  test do
    # Verify the binary at least starts and reports the expected error when
    # required env vars are missing. Exit code 1 means it ran far enough to
    # validate config — what we want.
    output = shell_output("#{bin}/edookit-mcp 2>&1", 1)
    assert_match "required env var", output
  end
end
