# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EdookitMcp < Formula
  desc "Unofficial MCP connector for Edookit (Czech school information system)"
  homepage "https://github.com/dsaiko/edookit-mcp"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dsaiko/edookit-mcp/releases/download/v0.1.2/edookit-mcp_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "9956a430ffe1ec7b7a11a5488967a8de5067a733e7cd3ae83eb4cef293453e7d"

      define_method(:install) do
        bin.install "edookit-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dsaiko/edookit-mcp/releases/download/v0.1.2/edookit-mcp_0.1.2_Darwin_arm64.tar.gz"
      sha256 "1f9afbc473b7a97b69916aca0d3ed9d6eaaaed54824feb3a764db77393dcc718"

      define_method(:install) do
        bin.install "edookit-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dsaiko/edookit-mcp/releases/download/v0.1.2/edookit-mcp_0.1.2_Linux_x86_64.tar.gz"
      sha256 "78f6183ba3dcbe2c0c437c63f03bcfcba2f13c385fb0fe146b2ee6c06061f642"
      define_method(:install) do
        bin.install "edookit-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dsaiko/edookit-mcp/releases/download/v0.1.2/edookit-mcp_0.1.2_Linux_arm64.tar.gz"
      sha256 "93dcb4710cbf03563fb97821be008ada02f4c1da231dc08a501032dcc1824e85"
      define_method(:install) do
        bin.install "edookit-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      edookit-mcp requires Google Chrome (or any Chromium-family browser) installed
      on the host — it drives a real browser instance once per ~10 hours to log into
      Plus4U OIDC and capture the session cookie.

      Configuration is via environment variables (EDOOKIT_URL, EDOOKIT_USER, EDOOKIT_PASS).
      See https://github.com/dsaiko/edookit-mcp#-pro-uživatele for full setup.
    EOS
  end

  test do
    # Verify the binary at least starts and reports the expected error when
    # required env vars are missing. Exit code 1 means it ran far enough to
    # validate config — what we want.
    output = shell_output("#{bin}/edookit-mcp 2>&1", 1)
    assert_match "required env var", output
  end
end
