# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EdookitMcp < Formula
  desc "Unofficial MCP connector for Edookit (Czech school information system)"
  homepage "https://github.com/dsaiko/edookit-mcp"
  version "0.1.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dsaiko/edookit-mcp/releases/download/v0.1.14/edookit-mcp_0.1.14_Darwin_x86_64.tar.gz"
      sha256 "374e8d2103197677816442b056bb3f8e76df4e37f1645c839a004ee1a05bf0e4"

      define_method(:install) do
        bin.install "edookit-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dsaiko/edookit-mcp/releases/download/v0.1.14/edookit-mcp_0.1.14_Darwin_arm64.tar.gz"
      sha256 "13eadbb50ddcbdc97867352b226c97df0794abf09c246e89f01f4d31b8dca306"

      define_method(:install) do
        bin.install "edookit-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dsaiko/edookit-mcp/releases/download/v0.1.14/edookit-mcp_0.1.14_Linux_x86_64.tar.gz"
      sha256 "284ad67aba5e3bd8fb36d7fcbf72904f3a184cd76b07331e2aaeaaff2b3eccbd"
      define_method(:install) do
        bin.install "edookit-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dsaiko/edookit-mcp/releases/download/v0.1.14/edookit-mcp_0.1.14_Linux_arm64.tar.gz"
      sha256 "c98051b1e596432f83e5b46e6f57bab6553dbafe01ed323e417e02866392c96e"
      define_method(:install) do
        bin.install "edookit-mcp"
      end
    end
  end

  def caveats
    <<~EOS
      edookit-mcp requires Google Chrome (or any Chromium-family browser) installed
      on the host — it drives a real browser instance once per ~10 hours to log into
      Plus4U OIDC and capture the session cookie.

      Configuration is via environment variables (EDOOKIT_URL, EDOOKIT_USER, EDOOKIT_PASS).
      See https://github.com/dsaiko/edookit-mcp#-pro-uživatele for full setup.
    EOS
  end

  test do
    # Verify the binary at least starts and reports the expected error when
    # required env vars are missing. Exit code 1 means it ran far enough to
    # validate config — what we want.
    output = shell_output("#{bin}/edookit-mcp 2>&1", 1)
    assert_match "required env var", output
  end
end
